version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 1000000000000ufury
  - 1000000000uatom
  - 1000000000uusd
  mnemonic: guard cream sadness conduct invite crumble clock pudding hole grit liar
    hotel maid produce squeeze return argue turtle know drive eight casino maze host
- name: bob
  coins:
  - 1000000000000ufury
  - 1000000000uatom
  - 1000000000uusd
  mnemonic: friend excite rough reopen cover wheel spoon convince island path clean
    monkey play snow number walnut pull lock shoot hurry dream divide concert discover
faucet:
  name: null
  coins: []
  host: 0.0.0.0:4500
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: ufury
    farming:
      params:
        private_plan_creation_fee:
        - amount: "100000"
          denom: ufury
    gov:
      deposit_params:
        min_deposit:
        - amount: "1"
          denom: ufury
      voting_params:
        voting_period: 20s
    liquidfarming:
      params:
        liquid_farms:
        - fee_rate: "0.000000000000000000"
          min_bid_amount: "1"
          min_farm_amount: "1"
          pool_id: "1"
        rewards_auction_duration: 120s
    liquidity:
      params:
        pair_creation_fee:
        - amount: "100000"
          denom: ufury
        pool_creation_fee:
        - amount: "100000"
          denom: ufury
    liquidstaking:
      params:
        liquid_bond_denom: bfury
        whitelisted_validators:
        - target_weight: "100000000"
          validator_address: furyvaloper13w4ueuk80d3kmwk7ntlhp84fk0arlm3mugy5fe
    mint:
      params:
        mint_denom: ufury
    staking:
      params:
        bond_denom: ufury
  chain_id: localnet
validators:
- name: alice
  bonded: 500000000000ufury
  home: ~/.redshift-1
