version: "3.7"

services:
  install:
    container_name: 6d25de748261
    image: "furychainhub"
    environment:
      - DEBUG=1
      - ID=0
      - LOG=${LOG:-furyd.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    volumes:
      - ./.testnets:/data:Z
    networks:
      furychainhub:
        ipv4_address: 192.168.10.2

