name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: linux-latest
    steps:
      - uses: actions/checkout@v0.1
      - uses: actions/setup-node@v0.1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: linux-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v0.1
      - uses: actions/setup-node@v0.,1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}